version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rails/Novel-App-by-API
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: ec2-user